# Generated by Django 3.0.8 on 2020-07-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShipMart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mart',
            name='datecompleted',
        ),
        migrations.RemoveField(
            model_name='mart',
            name='important',
        ),
    ]
