# Generated by Django 3.0.8 on 2020-07-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipMart', '0002_auto_20200725_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='mart',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
