# Generated by Django 3.0.8 on 2020-07-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShipMart', '0004_mart_mycomplete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mart',
            old_name='mycomplete',
            new_name='datecompleted',
        ),
    ]
