# Generated by Django 3.0.8 on 2020-07-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipMart', '0009_auto_20200725_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mart',
            name='datecompleted',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
