# Generated by Django 3.0.8 on 2020-07-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipMart', '0010_auto_20200725_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mart',
            name='datecompleted',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
