# Generated by Django 3.0.8 on 2020-07-25 15:52

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ShipMart', '0014_auto_20200725_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mart',
            name='datecompleted',
            field=models.DateTimeField(blank=True, default=django.db.models.fields.DateTimeField, null=True),
        ),
    ]
