# Generated by Django 3.0.8 on 2020-07-25 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipMart', '0017_auto_20200725_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mart',
            name='datecompleted',
            field=models.DateTimeField(blank=True, help_text=datetime.datetime(2020, 7, 25, 21, 27, 41, 355558), null=True),
        ),
    ]
