# Generated by Django 3.0.8 on 2020-07-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipMart', '0020_auto_20200725_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mart',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mart',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
