# Generated by Django 3.0.8 on 2020-08-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipMart', '0021_auto_20200725_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
